services:
  - type: web
    name: tenderbase-final-api
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /health
