import Fastify from 'fastify';
import { db } from './db.js';
import { EtendersClient } from './collectors/etenders/client.js';
import { persistRelease } from './collectors/etenders/importer.js';

const app = Fastify({ logger: true });
app.get('/', async () => ({ name: 'TenderBase API', version: 'v1', status: 'ok', docs: '/docs' }));
app.get('/health', async () => { await db.$queryRaw`SELECT 1`; return { status: 'ok', service: 'tenderbase-api', database: 'ok' }; });
app.get('/openapi.json', async () => ({ openapi: '3.0.3', info: { title: 'TenderBase API', version: '1.0.0' }, paths: {} }));
app.get('/docs', async () => ({ message: 'API documentation endpoint', openapi: '/openapi.json' }));

app.get('/internal/etenders-smoke', async (request, reply) => {
  const token = (request.query as any)?.token;
  if (!process.env.ETENDERS_SMOKE_TOKEN || token !== process.env.ETENDERS_SMOKE_TOKEN) return reply.code(404).send({ error: 'Not found' });
  const to = new Date(); const from = new Date(to.getTime() - 7 * 24 * 60 * 60 * 1000);
  const client = new EtendersClient(); const result = await client.getPageWithFallback(1, from, to);
  let succeeded = 0, failed = 0;
  for (const release of result.package.releases ?? []) { try { await persistRelease(release); succeeded++; } catch (error) { failed++; app.log.error({ err: error, releaseId: release.id }, 'Smoke ingestion failed'); } }
  return { from, to, pageSize: result.pageSize, releases: result.package.releases?.length ?? 0, succeeded, failed };
});

function pagination(q: any) { const page = Math.max(1, Number(q.page ?? 1)); const limit = Math.min(100, Math.max(1, Number(q.limit ?? q.pageSize ?? 25))); return { page, limit, skip: (page - 1) * limit }; }
function date(v?: string) { return v ? new Date(v) : undefined; }

app.get('/api/v1/tenders', async (request) => { const q = request.query as any; const { page, limit, skip } = pagination(q); const where: any = {}; if (q.status) where.status = q.status; if (q.province) where.province = q.province; if (q.category) where.mainProcurementCategory = q.category; if (q.buyerId) where.buyerId = q.buyerId; if (q.publishedFrom || q.publishedTo) where.publishedDate = { ...(q.publishedFrom ? { gte: date(q.publishedFrom) } : {}), ...(q.publishedTo ? { lte: date(q.publishedTo) } : {}) }; if (q.closingBefore) where.closingDate = { lte: date(q.closingBefore) }; const [items, total] = await Promise.all([db.tender.findMany({ where, orderBy: { publishedDate: 'desc' }, skip, take: limit, include: { buyer: true } }), db.tender.count({ where })]); return { page, limit, total, pages: Math.ceil(total / limit), items }; });
app.get('/api/v1/tenders/search', async (request) => { const q = request.query as any; const { page, limit, skip } = pagination(q); const where: any = q.q ? { OR: [{ title: { contains: q.q, mode: 'insensitive' } }, { description: { contains: q.q, mode: 'insensitive' } }] } : {}; if (q.province) where.province = q.province; if (q.status) where.status = q.status; const [items, total] = await Promise.all([db.tender.findMany({ where, orderBy: { publishedDate: 'desc' }, skip, take: limit }), db.tender.count({ where })]); return { q: q.q ?? '', page, limit, total, pages: Math.ceil(total / limit), items }; });
app.get('/api/v1/tenders/new', async (request) => { const q = request.query as any; const { page, limit, skip } = pagination(q); const since = date(q.since) ?? new Date(Date.now() - 7 * 86400000); return { page, limit, items: await db.tender.findMany({ where: { publishedDate: { gte: since } }, orderBy: { publishedDate: 'desc' }, skip, take: limit }) }; });
app.get('/api/v1/tenders/closing-soon', async (request) => { const q = request.query as any; const { page, limit, skip } = pagination(q); const until = date(q.until) ?? new Date(Date.now() + 7 * 86400000); return { page, limit, items: await db.tender.findMany({ where: { closingDate: { gte: new Date(), lte: until } }, orderBy: { closingDate: 'asc' }, skip, take: limit }; });
app.get('/api/v1/tenders/:id', async (request, reply) => { const { id } = request.params as any; const item = await db.tender.findFirst({ where: { OR: [{ id }, { ocid: id }] }, include: { buyer: true, procuringEntity: true, lots: true, items: true, documents: true, briefings: true, contacts: true, awards: { include: { suppliers: { include: { organization: true } } } }, contracts: true } }); if (!item) return reply.code(404).send({ error: 'Tender not found' }); return item; });
app.get('/api/v1/tenders/:id/raw', async (request, reply) => { const { id } = request.params as any; const tender = await db.tender.findFirst({ where: { OR: [{ id }, { ocid: id }] } }); if (!tender) return reply.code(404).send({ error: 'Tender not found' }); return tender.rawJson; });
app.get('/api/v1/tenders/:id/timeline', async (request, reply) => { const { id } = request.params as any; const tender = await db.tender.findFirst({ where: { OR: [{ id }, { ocid: id }] } }); if (!tender) return reply.code(404).send({ error: 'Tender not found' }); return db.release.findMany({ where: { ocid: tender.ocid }, orderBy: { date: 'asc' }, select: { releaseId: true, date: true, tags: true, description: true, rawJson: true } }); });
app.get('/api/v1/ocds/releases', async (request) => { const q = request.query as any; const { page, limit, skip } = pagination(q); const [items, total] = await Promise.all([db.release.findMany({ orderBy: { date: 'desc' }, skip, take: limit }), db.release.count()]); return { page, limit, total, pages: Math.ceil(total / limit), items }; });
app.get('/api/v1/ocds/releases/:releaseId', async (request, reply) => { const { releaseId } = request.params as any; const r = await db.release.findUnique({ where: { releaseId } }); if (!r) return reply.code(404).send({ error: 'Release not found' }); return r.rawJson; });
app.get('/api/v1/ocds/records/:ocid', async (request, reply) => { const { ocid } = request.params as any; const releases = await db.release.findMany({ where: { ocid }, orderBy: { date: 'asc' } }); if (!releases.length) return reply.code(404).send({ error: 'Record not found' }); return { ocid, releases: releases.map(r => r.rawJson) }; });
app.get('/api/v1/buyers', async (request) => { const q = request.query as any; const { page, limit, skip } = pagination(q); const [items, total] = await Promise.all([db.organization.findMany({ where: { roles: { some: { role: 'buyer' } }, ...(q.q ? { name: { contains: q.q, mode: 'insensitive' } } : {}) }, orderBy: { name: 'asc' }, skip, take: limit }), db.organization.count({ where: { roles: { some: { role: 'buyer' } } } })]); return { page, limit, total, items }; });
app.get('/api/v1/buyers/:id', async (request, reply) => { const { id } = request.params as any; const x = await db.organization.findUnique({ where: { id }, include: { roles: true, buyerTenders: { take: 20, orderBy: { publishedDate: 'desc' } } } }); if (!x) return reply.code(404).send({ error: 'Buyer not found' }); return x; });
app.get('/api/v1/buyers/:id/tenders', async (request) => { const { id } = request.params as any; const { page, limit, skip } = pagination(request.query); return { page, limit, items: await db.tender.findMany({ where: { buyerId: id }, orderBy: { publishedDate: 'desc' }, skip, take: limit }) }; });
app.get('/api/v1/suppliers', async (request) => { const q = request.query as any; const { page, limit, skip } = pagination(q); return { page, limit, items: await db.organization.findMany({ where: { roles: { some: { role: 'supplier' } }, ...(q.q ? { name: { contains: q.q, mode: 'insensitive' } } : {}) }, orderBy: { name: 'asc' }, skip, take: limit }) }; });
app.get('/api/v1/suppliers/:id', async (request, reply) => { const { id } = request.params as any; const x = await db.organization.findUnique({ where: { id }, include: { roles: true, suppliers: { include: { award: true } } } }); if (!x) return reply.code(404).send({ error: 'Supplier not found' }); return x; });
app.get('/api/v1/awards', async (request) => { const { page, limit, skip } = pagination(request.query); return { page, limit, items: await db.award.findMany({ orderBy: { date: 'desc' }, skip, take: limit, include: { suppliers: { include: { organization: true } } } }); });
app.get('/api/v1/tenders/:id/awards', async (request) => { const { id } = request.params as any; const tender = await db.tender.findFirst({ where: { OR: [{ id }, { ocid: id }] } }); return tender ? db.award.findMany({ where: { tenderId: tender.id }, include: { suppliers: { include: { organization: true } } } }) : []; });
app.get('/api/v1/tenders/:id/documents', async (request) => { const { id } = request.params as any; const tender = await db.tender.findFirst({ where: { OR: [{ id }, { ocid: id }] } }); return tender ? db.document.findMany({ where: { tenderId: tender.id } }) : []; });
app.get('/api/v1/statistics/tenders', async () => ({ tenders: await db.tender.count(), releases: await db.release.count(), sourceRecords: await db.sourceRecord.count(), organizations: await db.organization.count(), awards: await db.award.count(), contracts: await db.contract.count() }));
app.get('/api/v1/statistics/provinces', async () => db.tender.groupBy({ by: ['province'], _count: { _all: true }, orderBy: { _count: { ocid: 'desc' } } }));
app.get('/api/v1/statistics/categories', async () => db.tender.groupBy({ by: ['mainProcurementCategory'], _count: { _all: true }, orderBy: { _count: { ocid: 'desc' } } }));

const port = Number(process.env.PORT ?? 10000); const host = process.env.HOST ?? '0.0.0.0'; app.listen({ port, host }).catch(async error => { app.log.error(error); await db.$disconnect(); process.exit(1); });